### ISSUE TITLE
Make move command less special

### ISSUE THREAD

**Issue by shawncplus** [shawncplus/ranviermud#106]
Right now `_move` is a magic hidden command that is the backbone of how movement works. Make this command not magic (i.e., rename it `move`, don't hide it, and make `CommandParser` look at a `moveCommand` config to send movement to. This will allow players to literally type `move east` in addition to just `east`

**Comment by marado** [comment]
I'm used to see this as 'go', not 'move'... Should we catch the train and
go for a rename?

**Comment by shawncplus** [comment]
Commands can be aliased just by saying `aliases: ["go"]` in the move command
