### ISSUE TITLE
NPC Inventory and Drops

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#110]

**Comment by shawncplus** [comment]
NPCs already have an inventory but personally I think their inventory should be different than their drop table. Drops should be generated on death from a different pool

**Comment by seanohue** [comment]
👍 as long as it is possible to set it so that they drop their inventory, as well as having NPCs equip/unequip/loot via scripts.

**Comment by shawncplus** [comment]
yeah I mean, whatever happens on player/mob death happens inside the `core-combat` bundle at the moment. So whatever we build in core is just a "default" and could be completely overridden

**Comment by shawncplus** [comment]
Closing this as it's being handled in #111
