### ISSUE TITLE
Loot tables

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#111]

**Comment by samjaninf** [comment]
This is just an idea, but what about a loot system using word modifiers? E.G. 'Savage' Axe Brutality would give like a 10% extra crit damage. While a 'Bloody' Axe Brutality would only give 5%.

Just food for though.

**Comment by shawncplus** [comment]
So the loot system is going to work much like the other systems:

1. An abstract library to provide a scaffold for more customized methods to plug into
2. A basic implementation of an example method.

Take for example `core-combat` Combat isn't actually a "feature" of the core, it's an artifact of how the core works. So `core-combat` is just a plugin that ships with Ranvier that adds combat.

Loot will work very similar:

There will be base core functionality that defines a thing called a "loot table" which won't even be attached to Npcs directly. The rest of the implementation of how loot is dropped doesn't even take place in the core code. It will happen in bundles that I envision working something like so:

* Have some kind of base `LootTable` class that takes something like a probability map of item to probability
* The `core-areas` bundle will be updated such that one of the Npcs definitions has a loot table
* A new `core-loot` bundle will be created that will add a `lootable` NPC behavior
* Behavior will have a `killed` listener that will load the the loot table for that Npc
* a random number is generated
* items from the loot pool are picked
* a corpse is generated
* items are placed in the corpse

People that didn't want this functionality would just disable the `core-loot` bundle and create their own `lootable` behavior that could really do whatever the heck they want. I happen to agree that random generation of items is a cool idea. But for _base_ functionality I think just having a static list of static items to pick from is enough

**Comment by Xarcell** [comment]
I agree with samjaninf 

We should hasve a list of words that can be prepended to items that adds to the description, but also adds value. This would alsdo be used in random loot generation with random descriptions. Examples:

Simple Short Descriptions With Added Values
bloody:0
brass-studded:5
leather-engraved:3
diamond-carved:20
beveled:4
ruby-inlaid:800

If this is added to system mechanics, I will create a more rebust list.

**Comment by seanohue** [comment]
Really, whatever system is in place just needs to be flexible/configurable
enough to fit any kind of loot/item description you can imagine. For
example, I'd like to have a wide variety of tables based on the NPC type,
the environment they're found in, and other factors, and procedurally
generate everything, but as long as the base Loot API is flexible, (i.e.,
take tables or a single table as input, choose/generate a bit of loot or
more than one bit of loot, drop said loot) it will be easy to mod.



Sean O'Donohue
--
*Web Application Developer*
*GM NGI Onsite Team*

**Comment by samjaninf** [comment]
I agree with seanohue. My system was just a suggestion and using the bundles that shawn is putting in that could be fairly easily implemented.

Now I very much like the idea of a little procedural generation of loot and maybe mobs. The script would take a look at area, weather, type of mob and then also randomizes a few variables such as the basic type and the rarity/strength before looking at any special modifiers on the mob. Maybe that last one should come first in case the mob is marked nodrop and save some of that calculation time. Maybe somehow even check if any of these items exist out in the world and restrict it. Using those numbers it would pull from a table of weighted items.

'Frostmoon, carver of bones' would much more likely to be found in a glacial palace after killing a boss or like a rare type monster. Or maybe it would be found in a volcano as that is the only thing restricting its power, either way, I'm looking forward to it.

And the bundle system appears to be flexible enough to handle most if not all of that.

Random question. Do mobs have primitives?

**Comment by shawncplus** [comment]
@samjaninf not sure what you mean by primitives?

**Comment by samjaninf** [comment]
Say for instance you have an Orc. The orce has 5 str, 5 dex, 5 con, 5 int, 5 wis as an example. Then you create an orc captain from that base orc and you assign the captain 5 str, 5 con and 5 int. The captain would then end up with 10 str, 5 dex, 10 con, and 10 int. Then you create an orc guard from the basic orc and gave it 5 con and 5 dex. The guard would end up with 5 str, 10 dex, 10 con, etc etc.

I'm pretty bad at explaining my thoughts so I thought providing an example would be a better idea.

**Comment by shawncplus** [comment]
This is partially implemented. Remaining todo list:

* Allow corpses to decay
* Allow multiple loot tables on an NPC. I.e., I want this NPC to have its own loot table in addition to a world drop list, for example

**Comment by shawncplus** [comment]
We now have loot tables, item quality, and corpse decay. I'm calling this one closed with prejudice
