### ISSUE TITLE
Hotboot

### ISSUE THREAD

**Issue by shawncplus** [shawncplus/ranviermud#113]
Need ability to hotboot anything from a bundle into the game without taking down the server.

**Comment by jackjwilliams** [comment]
Any recommended paths forwards on this? While I'm working on help files, this would be really nice. Willing to look into it. Are you thinking of some kind of file watcher, or maybe an explicitly executed command on the server side maybe?

**Comment by jackjwilliams** [comment]
Or maybe in conjunction with a startup arg, --watchBundles

**Comment by seanohue** [comment]
Having it be a file watcher would be interesting. I think the MVP is to have it be a server-side command.

**Comment by shawncplus** [comment]
Hotloading is a tricky issue mainly because of keeping players connected. The best approach would be to save all players, replace them with new `Player` instances, move the socket over to the new instance, and replace their old instance in `PlayerManager`. Then the game could essentially just reset all of the `GameState` except for `PlayerManager` and call `BundleManager.loadBundles()` again

**Comment by shawncplus** [comment]
Moving hotboot out of v1.0.0. Should document the correct process which is to have dev and live checkouts of Ranvier. Development should happen on the dev checkout on a different port, make changes there and test them on the dev server. Once they're ready commit them then pull them into the live checkout and only restart once.

**Comment by seanohue** [comment]
Will this issue be closed in favor of the `hotfix` command?

**Comment by shawncplus** [comment]
Closed with e2f9a345eef219e39909247470c61e4cd82aaed2
