### ISSUE TITLE
Combat Stances

### ISSUE THREAD

**Issue by Xarcell** [shawncplus/ranviermud#114]
Implement 3 Stances
1.| Offensive +50% attack, -50% Defense
2.| Neutral(default): +0 attack, +0 defense
3.| Defensive: -50% attack, +50% defense

This would help characters grind, survive passing through high level areas, and add advance combat strategies.

**Comment by shawncplus** [comment]
Sounds like a neat custom bundle, can currently be implemented as a bundle with no updates to the core needed.
