### ISSUE TITLE
Skill Leveling

### ISSUE THREAD

**Issue by Xarcell** [shawncplus/ranviermud#117]
I would like to see an option for skill leveling, instead of whole character leveling. IMO.

**Comment by shawncplus** [comment]
There's no need for an "option" all the currently "leveling" code happens in the bundle. For example, if I'm building a MUD with ranvier I would _not_ want skill leveling.

Bundles allow you to customize basically everything without the need for options or toggles in the core. The core fires off events and bundles can be added to modify functionality.

For example leveling happens _entirely_ in the `core-player-events` bundle. If someone doesn't like how that bundle handles leveling they just need to disable the bundle by removing `core-player-events` from `ranvier.json` and add their own that subscribes to the `experience` event
