### ISSUE TITLE
Balanced Leveling

### ISSUE THREAD

**Issue by Xarcell** [shawncplus/ranviermud#118]
Easy success gives less experience.
Hard success gives more experience.

Possible Formula:

A = Difficulty Of Event
B = Character Ability

A - B = experience

**Comment by shawncplus** [comment]
@Xarcell Just as an FYI these issues that I'm labeling Bundle are things that wouldn't be implemented in Ranvier, they're things that would be part of a Bundle http://ranviermud.com/extending/bundles/
