### ISSUE TITLE
Similarly to commands, helpfiles should have searches by keyword.

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#142]
Right now a set of keywords can be defined for a helpfile, but they are not implemented by the `help` command or `HelpManager` when a user searches for help on a topic.

**Comment by shawncplus** [comment]
I think this is because I had the idea to have a `help search` command that would just do full text searches for relevant helpfiles but halfway through implementing them I... forgot?

**Comment by seanohue** [comment]
Yeah, I figured it was a "nice to have" that you had the foresight to include some stub functionality for.

**Comment by seanohue** [comment]
I think this was closed by #146

**Comment by seanohue** [comment]
(unless we want to implement essentially grepping helpfiles?)

**Comment by shawncplus** [comment]
Nah, this is good enough for the search at the moment. I originally envisioned full text search of helpfiles but that's a progressive enhancement that can be added later.
