### ISSUE TITLE
Blacklisting certain player names

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#145]
I'd like to see this for a few reasons, implemented in a couple of ways:

1) Built into core, we should auto-blacklist players from having the exact same name as NPCs or items unless we provide a way to specify that the target is a player, such as a prefix. For example, if we added PvP, I could avoid combat by naming myself Rat and standing in the same room as a rat and hoping for the best. This could be done dynamically.

2) Configurable blacklist via ranvier.json... not sure if we would want to have them list an array of strings since that could be huge. Perhaps it could be a path to a json/csv/yaml file that is a blacklist, or perhaps it could be something easily packaged into a bundle so that a regex could be used. This could make it so admin could blacklist swear words, or names that might break immersion (if they desire to do so), without editing core too heavily.

**Comment by shawncplus** [comment]
Rethinking this, this definitely doesn't need to be in core and can be handled completely inside a bundle since all of the creation of players/accounts happens in the input events
