### ISSUE TITLE
Figure out testing framework setup

### ISSUE THREAD

**Issue by jackjwilliams** [shawncplus/ranviermud#149]
I did an initial pass at trying to create some test classes for the main parts of the system. The main difficulty was loading a test game state. I modified BundleLoader.loadBundles to take a srcPath and bundlePath, and made sure the normal engine ran as expected, and it did. But there were other questions.

1. We will likely need our own test data set (various test bundles of rooms / scripts / items / npcs / etc...). But we wouldn't want to modify the core-* bundles. How can this be achieved? If I point BundleManager to my "/test/bundles" folder, I would have to copy all the core into it to test those pieces?

2. Maybe we could designate core-* bundles as required, with a custom-bundles folder for customization? This could separate out that requirement as BundleManager knows exactly the core bundles to pull (/bundles) for core functionality, and custom bundles (/custom-bundles, or /test/test-bundles).

Just thinking out loud.

**Comment by shawncplus** [comment]
`core-*` bundles aren't required. IMO tests should only ever test code in `src/` and none of `src/` _requires_ bundles to exist (outside of the bundle loader itself but even then the bundle loader doesn't actually care what's in them)
