### ISSUE TITLE
Looking at an item in a container

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#161]
I would expect to be able to look at the description of an item in a container.

Syntax could be something like `look <item> in <container>` or `look <container> <item>`, not sure which is more favorable.

**Comment by shawncplus** [comment]
I don't think that was actually possible in Diku/SMAUG so I'm not going to worry too much about this one

**Comment by shawncplus** [comment]
Really I'm more concerned about building the breadth of commands now more than making the basic ones super feature-full. So I'd say try to think of commands that might be missing that you're used to in other MUDs that weren't specific to that MUD's featureset. Stuff like `emote`, `sleep`, `score`, `list/sell/buy`, etc.

**Comment by seanohue** [comment]
Yeah, I've been thinking about emote, too. I'll make issues for that.
