### ISSUE TITLE
Emoting

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#163]
I would expect emoting to, at a minimum, allow me to do things like this:

`> emote dances a jig.`

And I would see:
`>You emote "Sean dances a jig."`

And others would see:
`>Sean dances a jig.`

To extend this, it would be nice to have shorthand (`:` is conventional, I think), and potentially to be able to refer to specific characters or entities using `~`. However, these features might be something for post-1.0 or for individual bundle developers to figure out.

**Comment by marado** [comment]
I'm not sure there's a need for the feedback to the user to be distinct from the output to all others in the room. ie, mostly I see emote implemented as:
```
emote dances a jig.
Sean dances a jig.
```

I agree that `:` is the most popular shortcut to the emote command.

**Comment by seanohue** [comment]
I agree with the exception that your emote targets a specific entity (player, NPC) in the room.

However for an MVP it is probably fine to exclude that.

**Comment by shawncplus** [comment]
Closed with #268
