### ISSUE TITLE
Legibles

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#165]
Legibles are a common feature in virtual worlds, in the form of in-world signs, player-written newspapers, OOC message boards, books, and more. 

It'll be a bit of an undertaking to implement _all_ of the desired/possible features, but an MVP would be the ability to `read <legible>` and see some nicely formatted text. In addition, after a certain length, the text should be paginated. I hate the way that most MUDs handle pagination, and would personally do it with subcommands like `read next <legible>` or `read previous <legible>` to flip through a book, and `read page <number> <legible>` to read a specific page.

**Comment by shawncplus** [comment]
I'm not entirely sure how this isn't just an item with a description at least for the MVP.

**Comment by seanohue** [comment]
Sorry, to clarify, the MVP would include the pagination. I left off mid-thought. 

Beyond the MVP of having paginated, readable items, would be:

- Writeable, fixed items such as in-game bulletin boards that players could add a note to and read notes from.
- Writeable carried items such as letters, notes, books/journals, etc.
