### ISSUE TITLE
Consumables

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#169]
Food, drink, potions, etc.

Should be paired with commands such as `eat`, `drink`, and the classic `quaff`. 

Food and drink could (in the default bundles at least) restore small amounts of health/energy, probably no need for realistic hunger/thirst. Potions would give some kind of more interesting effect when consumed. 

Discussion question: Should we try implementing liquid containers so that drinking a potion leaves you with an empty flask, or should the entire potion just disappear?

**Comment by shawncplus** [comment]
It's easier and I prefer when the potion just disappears. It's only useful to keep the flask if brewing were a thing and you could make another potion with that flask
