### ISSUE TITLE
Basic shop functionality

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#172]
The logic for an in-game shop could be based around the following:

- A `shop` behavior that could be attached to an NPC, a room, or an item (for example, a vending machine). This would be configured with IDs of the items available, the quantity available (defaulting to infinite), and the cost.

- A `list` command that would list all items available at the shop if applicable.

- A `buy` command that would allow purchase if the player has enough currency. `buy <item or #>`

- A `sell` command that would allow the player to sell one of their items for currency if the shop allows. A nice-to-have would be having the shop keep the item in its inventory, at least until reboot.

One prerequisite for this is currency.

**Comment by shawncplus** [comment]
OTOMH I'd say this could be done with a behavior like lootable where the config is just a list of items for sale and their price. But yeah, definitely need currency

**Comment by shawncplus** [comment]
Closed with a78e0feacf40abcc915571506c78419a9ab6244d
