### ISSUE TITLE
"Give" command

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#173]
To avoid the only form of item trading being via dropping items on the floor for someone else to pick up, we could implement a `give` command. It would work similarly to `put`, but the target would be another player or even NPC in the same room. 

Potentially, we could make it so that the recipient has to `accept` the gift but that is more of a nice-to-have.

Syntax: `give <item> [to] <target>`

**Comment by shawncplus** [comment]
I think an important part of this is a behavior for NPCs that would allow them to accept certain items. By default giving an item to an npc should reject the command so the player doesn't accidentally lose items.

**Comment by shawncplus** [comment]
Closed in 5ca682649114e2407361924f6277d0b44a1e89ca
