### ISSUE TITLE
"Aggro" mobs

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#176]
Could add a behavior for NPCs to auto-attack when an event is triggered. Defaults to a player entering the room. Could be tricky to make it handle a wide variety of events though.

The configuration could look like this:
```
behaviors:
    aggro:
        event: "playerEnter"
```

Could also be used to make guard NPCs attack when a player picks up (read: steals) certain items, etc.

**Comment by shawncplus** [comment]
Added in 1f3ac1051a92e4e76031e8fb73db2785baa5bf52
