### ISSUE TITLE
"Scan" command

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#177]
I'd like to be able to `scan` the area to see what is in adjacent rooms, such as `scan <exit>`. Kind of like `look` but takes a direction. Could also just mean altering `look` to understand things like `look <exit>` but having a separate command could prevent collisions for when I want to look west but some jerk made a character named Westminster, or something like that. 

Not sure if we'd want to show them the room desc or just the title and any players, NPCs, and items.

**Comment by shawncplus** [comment]
I think the most basic case is just a `scan` command that doesn't take a direction and lists NPC/Players in adjacent rooms.
