### ISSUE TITLE
"Consider" command

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#182]
Typing `consider <character>` should give you an idea of whether the other character is stronger or weaker than you (shorthand for "consider attacking <character>"). Not sure if this is a Diku thing or not but most non-IRP MUDs have this.

Example:

```
> consider rat

A Large Rat would put up a fair fight.

> consider castle guard

A Castle Guard would massacre you.
```
Potentially with color coding:
Red if they are much higher level.
Yellow if they are slightly higher level.
Blue if they are the same level.
Green if they are a lower level.

**Comment by shawncplus** [comment]
Yeah I don't know if this originated with diku but it's definitely in basically every MUD
