### ISSUE TITLE
Kick Idle Players

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#204]
### Description

As an admin, I'd like to be able to configure a maximum idle time and kick players above that threshold.
If there is no idle time set, players will not be kicked.
This might require a few changes to see when the player last entered a command, but I don't think it would require any major refactors.

### Expected outcome
Idling forever can lead to being kicked.

### Actual outcome
I can idle infinitely without being kicked and there is no way to configure otherwise.

### Steps to reproduce
Idle forever.

### Version of Ranvier
1.0.1

**Comment by samjaninf** [comment]
Might just implement a timer per person. Every tick updates timer. If any values on timer list greater than timeout value set in ranvier.json (or where ever) then kick. Could even have it check if it's enabled before every tick and just not update that or just set it to 0.

Every input entered would of course drop their counter back to 0... Unless there is no common input handler/point...

**Comment by seanohue** [comment]
That could work. The common input handler would be the command parser or command event.

**Comment by shawncplus** [comment]
The command event would be the better place to put it.
