### ISSUE TITLE
Unable to request access to slack channel

### ISSUE THREAD

**Issue by m4l1c3** [shawncplus/ranviermud#214]
It appears that requesting a slack invite isn't working, the following error occurs when attempting to request an invite.

![slack-error](https://cloud.githubusercontent.com/assets/5158588/25619584/a8a61c74-2f08-11e7-9dee-530e866828d3.png)

**Comment by shawncplus** [comment]
Interesting, maybe there's was something going on with signup.team which is the service I was using. Are you still having the issue?

**Comment by m4l1c3** [comment]
Things appear to be working now, thanks!
