### ISSUE TITLE
Who can display 0 players

### ISSUE THREAD

**Issue by criticalfault** [shawncplus/ranviermud#233]
### Description
 who

                  Who's Online
===============================================

0 total

 
### Expected outcome
Should display the proper amount of connected players
### Actual outcome
Player count on who can be zero

 
### Steps to reproduce
I logged in and my buddy logged in. I had him save, log out. I edited his json file to changed his role to 2 and when he logged in and then off. Our player count was reduced to 0.

**Comment by seanohue** [comment]
Thanks for submitting this!

I'm going to try reproducing this as is, and also reproducing it without changing the player's role to see if that is a factor.

**Comment by seanohue** [comment]
Really odd: I was not able to reproduce, either by following the steps directly or by attempting to reproduce without changing the player role. The `who` command always said either 1 or 2 players and, in the end, said 1 player. 

Then again, both of my connections were local (on the same machine as the server) so maybe it is a network-related issue of some kind? Will try again while connecting to a remote server.

**Comment by seanohue** [comment]
@criticalfault Was this bug present on `master` of ranviermud, on `staging`, or on a fork of yours? If it's the last one, can you post a link to it? Thanks.

**Comment by shawncplus** [comment]
Gonna close this as CNR, haven't seen anyone able to replicate this
