### ISSUE TITLE
Consider Not Working

### ISSUE THREAD

**Issue by thedandroid** [shawncplus/ranviermud#236]
### Description
Consider command shows no feedback. Logger isn't defined and player.findCombatant() on line 19 should be Combat.findCombatant(), but then it looks like the variable e on line 20 is undefined any time the command is used on an entity that cannot be attacked (e.g. pacifist, non-pvp player).

### Expected outcome
Consider should show it's feedback or spit out it's proper error.

### Actual outcome
Consider shows nothing.

### Steps to reproduce
Use the consider command on something. With the two little fixes above, use the consider command on an entity that cannot be attacked.

### Version of Ranvier
1.1.1

**Comment by seanohue** [comment]
I would love to consider not working, but I need the money.

*reads the rest of the issue*

Ah, nevermind.
