### ISSUE TITLE
Consider gives incorrect error messages

### ISSUE THREAD

**Issue by thedandroid** [shawncplus/ranviermud#237]
### Description
Consider command gives "They aren't here" instead of the proper error message.

### Expected outcome
Proper error messages, e.g. "They are a pacifist", etc.

### Actual outcome
"They aren't here."

### Steps to reproduce
Consider any NPC that is a pacifist.

### Version of Ranvier
1.1.1

**Comment by shawncplus** [comment]
Closed in #238
