### ISSUE TITLE
Mention that yaml files cannot be formatted with tabs

### ISSUE THREAD

**Issue by quakeboy** [shawncplus/ranviermud#24]
I used Sublime Text 2 and I indented the file with tabs and it refused to load.
I had to choose the "Convert indentation to spaces"

Spent an awful lot of time trying to figure out why the server wasn't able to parse my yml files sucessfully

**Comment by ingcake** [comment]
That's a language-specific issue.  A link to the YAML [documentation](http://www.yaml.org/spec/1.2/spec.html) and tutorial might be more generally useful, but those are easily Google'd. Wouldn't this suggestion be akin to adding "code lines must end with a semicolon" to the README of a C project? (I know this is necromancy, but I'm hoping Shawn will come through and close issues once resolved.)

**Comment by marado** [comment]
This was fixed with https://github.com/shawncplus/ranviermud/wiki/Home/_compare/b3b37f3f1541b58bfabab782f48ea87fd5e81d75...c089433a47faa08fd6c25209341a09c44cdd4497?short_path=b4d7124#diff-b4d7124d2993cd13aabeec1fc19baf51 , and should be closed.
