### ISSUE TITLE
Feature request: Ability to run Ranvier as a dependency and specify bundle paths via a CLI argument

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#241]
### Description

This might seem kind of left-field, but it would be cool to be able to access the Ranvier `src` and server as an npm module or library, and to be able to pass it a directory where it would load all bundles from, as well as specifying a path to the `ranvier.json` file via a CLI arg.

### Expected outcome

Can use Ranvier as a library/standalone server dependency and provide own bundles/configuration.

### Actual outcome

Can use Ranvier as a fork and nested package.jsons as a way to install individual bundles.

### Steps to reproduce
I dunno. Delete this if it's too out-there.

### Version of Ranvier
v1.1.1 (or any version)

**Comment by shawncplus** [comment]
This is certainly an interesting though, I'll have to stew it over. I like it in principle, just don't know the details in practice.

**Comment by coldwinter2** [comment]
Maybe, just like the Mudos
Defined path for mudlib via A config file 

https://github.com/lnsoso/mudos

**Comment by shawncplus** [comment]
Thinking about this more I still like the idea in concept but it creates some fairly major problem. If we move `src/` into a node module people then cannot edit the code without doing a hard fork of the node module which completely loses the ability to pull in updates without a giant hassle. It's better if you assume people are git masters, it's much worse for the average developer.

**Comment by seanohue** [comment]
Closing this since, while it could be super cool, it's a far-future addition and maybe not worth the work. Wacky late-night ideas, eh?
