### ISSUE TITLE
Allow items to be equipped in multiple slots.

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#249]
### Description

Example: You want to implement the ability to hold two items at once, one "wielded" and one "offhand". Currently, the `Item` class only allows for a single `slot` to be described, as a string. So if I have a candlestick that I equip and it goes into the 'wielded' slot, and then I try to equip a pitchfork, I will receive an error message telling me I cannot hold both. One potential solution is to allow item.slot to be defined as either a single slot (a string) or multiple slots (an array of strings). If it has multiple defined slots, then equip can do one of two things:
1) Try each of the slots in order until it finds an empty one, or throw an error if it does not find an open slot.
2) Take an optional second argument `equip pitchfork offhand` to specify an equipment slot. If the specified slot is not included in the pitchfork's array of slots (such as `equip pitchfork sandwich`), then throw an error, otherwise try to equip the item in that slot (succeeding or failing as normal).

### Expected outcome

Items can have multiple equippable slots.
Trying to equip an item with multiple equippable slots will try the slots in order until finding an open one or failing.
You can specify a slot to attempt to equip the item in.

### Actual outcome

Items only have one slot and there can only be one equipped item per slot.

### Steps to reproduce

Try creating an item with multiple slots. You can't do it. I double-dare you.

### Version of Ranvier
v1.1.1

**Comment by shawncplus** [comment]
Closed in d0677515fc0c63e6901831ad7e34a087508d864b
