### ISSUE TITLE
Backspace doesn't work in windows telnet.

### ISSUE THREAD

**Issue by miki123211** [shawncplus/ranviermud#252]
### Description
When connecting to ranvier with windows telnet, backspace isn't interpreted correctly.
This means that almost all commands with backspaces in them fail and we have to retype them from scratch.
### Expected outcome
If we accidentally type ';' instead of l, press backspace to erase the character and then type l, the look command should get executed.
### Actual outcome
The game just displays 'Huh?' in this case. This means the command doesn't get recognized.
### Steps to reproduce
On windows Wista and newer.
1. Go to control panel.
2. Select Programs and features.
3. Click enable or disable windows features (I'm not sure how exactly it's called in the english version of windows.).
4. Check the "telnet client" feature and click ok.
On all windows systems.
5. Press windows + r, wait for the run dialog to appear and then type telnet <hostname> <port> where hostname and port are your ranvier's hostname and port, you can use both your local server as well as the official one to test this.
6. After pressing enter, telnet should appear and you should see the message of the day, this means you're successfully connected.
7. Try typing a few letters of some nonexisting character name, erase them with backspace and then type your real character name and press enter.
8. The game won't recognize your name even though you typed it correctly.
### Version of Ranvier
1.1.1

**Comment by ZackWard** [comment]
I believe that this is actually an issue with the Windows telnet client. Most clients accumulate data as the user types, and then send a string when the user hits enter. Microsoft Telnet sends each character as it is typed.

**Comment by shawncplus** [comment]
Closing as I'm not sure there is a way to fix this, it seems to affect every mud I can find
