### ISSUE TITLE
Would be awesome to have hidden doors, like secret passages on rooms

### ISSUE THREAD

**Issue by marcelomoreli** [shawncplus/ranviermud#260]
I'd love to see hidden doors and also Locked hidden doors on rooms. These doors should not show on the "Exits" options (Maybe show to admins with some identifier or color).

**Comment by shawncplus** [comment]
So the player could go in the direction if they type it, it's just hidden?

**Comment by shawncplus** [comment]
My suggestion for implementing this without needing to fix core would be the following: use the `roomcommands` behavior (see: `bundles/ranvier-areas/areas/limbo/rooms.yml` for the Room commands test room with `bundles/ranvier-areas/areas/limbo/scripts/rooms/10-context.js`) Which would effectively create a room-specific command with the name of the exit and you would make the command move the player

**Comment by marcelomoreli** [comment]
Would be interesting to be a real hidden door, so that we can interact with skills like pick lock for locked ones, or a skill to "spy" the exit of that room

**Comment by shawncplus** [comment]
kk that's a small core change then. I've marked it as `New Contributor` because it's a pretty tiny addition.

**Comment by marcelomoreli** [comment]
Ok. Thank you!

**Comment by shawncplus** [comment]
This can now be done in bundles with the completion of #259.

Add the following to the room:

```
metadata:
  hidden: true
```

Then update the `look` command to filter out exits that are hidden. So in the case of `bundles/ranvier-commands/commands/look.js` you would first copy/rename the `ranvier-commands` bundle, disable the `ranvier-commands` bundle and enable your copy. Then change:

```
const directionsAvailable = room.exits.map(exit => exitMap.get(exitDirection));
```
to
```
const directionsAvailable = room.exits.filter(exit => !exit.getMeta('hidden')).map(exit => exitMap.get(exitDirection));
```

**Comment by shawncplus** [comment]
Yeah, no core change is needed for this, exits already let you set whatever arbitrary properties you want on them besides the defaults and they get read in. So just add `hidden: true` to the exit and update your `look` command to filter out exits with hidden: true

**Comment by marcelomoreli** [comment]
That will work perfectly, thanks!
