### ISSUE TITLE
When a item is loaded from the equipment of a player, it's not added on the "belongsTo" of the item.

### ISSUE THREAD

**Issue by marcelomoreli** [shawncplus/ranviermud#271]
When a player joins the game with some equipment equipped, if you check the item on ItemManager, it will not contain the player in the belongsTo of the item.

Additionally, I created a backpack to test with wearing a backpack with an item inside, to see if it would load correctly on the belongsTo, but actually it chashes the MUD, so I was unable to test it. Would be good to fix this crash as well.

**Comment by shawncplus** [comment]
So this is slightly confusing but `belongsTo` does not denote the _player_ it belongs to, it denotes the entity it belongs to which could either be the player if the item is directly in their inventory or it could be an item if it's inside a container.

**Comment by shawncplus** [comment]
That said, it does look like there is a bug on line `210` of Player.js where `newItem.hydrate` isn't sending the belongsTo so perhaps that's the issue you're running into.

**Comment by marcelomoreli** [comment]
Yep! Got it. But I was expecting that when the player is wearing something, the belongsTo would be the player.

I would also expect that if I have a sword in a bag, and I'm wearing the bag, the bag would have belongsTo = player and the sword belongsTo = bag, but that crashed the mud, hidrate didn't work for a item inside of a bag that I'm wearing,

**Comment by shawncplus** [comment]
> I would also expect that if I have a sword in a bag, and I'm wearing the bag, the bag would have belongsTo = player and the sword belongsTo = bag

Yep, this is definitely a bug
