### ISSUE TITLE
Aliases capability

### ISSUE THREAD

**Issue by marcelomoreli** [shawncplus/ranviermud#273]
would be great to have `aliases` so that we can execute several commands with just one command.

Examples:
alias eatbread get bread backpack; eat bread; say Ah! Delicious; -> Creates the alias
eatbread -> Execute the alias
alias eatbread -> Delete the alias
alias -> lists the current aliases

**Comment by shawncplus** [comment]
This is  more of a bundle thing than a core thing, there wouldn't need to be any core changes to add this functionality. I don't think it really needs to be added to the example bundles. This goes back to my philosophy that Ranvier's default bundles should be an _example_ implementaiton, not a full game in a box where you don't have to do any work.

**Comment by marcelomoreli** [comment]
Completely agree
