### ISSUE TITLE
Implement coordinate system

### ISSUE THREAD

**Issue by shawncplus** [shawncplus/ranviermud#275]
Details:

Every room definition should now have an optional `coordinate` property which is an array of `[x, y, z]`. The room will be stored exactly the same as it is now (inside RoomManager.) Additionally the Area object will be updated to contain a graph (node map) of the area's rooms based on the coordinates of its rooms. This can be used to draw minimaps and the like and will act as a real euclidean 3-dimensional plane.

If a room does not specify coordinates it will still be placed in the room manager and the area's room list but will not be in the area's room graph.

If an exit is not explicitly specified for a room the `move` command inside the `ranvier-commands` bundle will need to infer the possible exit room exits by looking at the area's graph.

Doors should still work... somehow, gotta spend some time with that one. It might "Just Work™️" but I'm not hopeful.

**Comment by pointybird** [comment]
Is this system going to be opt-in, ideally bundle-based with the old behavior still available? I'm hoping, like many others I presume, to move an existing game over to ranvier. I currently have about 150 zones converted from an existing diku and everything currently maps over without problem. Having to change everything to a new system would be ... unpleasant.

**Comment by shawncplus** [comment]
If you don't change anything everything _should_ still work as it did before, this _should_ be a purely additive change. So I think I should specify that the `coordinates` property is optional. If a room doesn't have a coordinates property you can still get to it by explicitly naming it as an exit destination but it won't appear in the area's graph object
