### ISSUE TITLE
GMCP support

### ISSUE THREAD

**Issue by vadi2** [shawncplus/ranviermud#276]
Is GMCP (out-of-band JSON) or any other out-of-band communications protocols supported?

**Comment by shawncplus** [comment]
The core doesn't have any real opinion about it, the implementation of the network layer is customizable. There is currently a `ranvier-telnet` bundle but it doesn't do any GCMP. So if someone wanted to implement GCMP they could use that bundle as a base and implement their GCMP code on top of it without changing the core.

**Comment by vadi2** [comment]
Ok, that's a pity, I think this should come as a standard with a modern MUD
engine.

**Comment by shawncplus** [comment]
The point of the engine is that it's not opinionated, even about the network layer. If someone wants a networking layer is that has GCMP they're free to use whatever telnet library they want and hook that into Ranvier.

**Comment by shawncplus** [comment]
@vadi2 As of the latest commit ranvier does support GMCP, see https://github.com/shawncplus/ranvier-telnet for usage.

**Comment by vadi2** [comment]
Awesome, thanks!
