### ISSUE TITLE
Alternative skill or level systems?

### ISSUE THREAD

**Issue by LoidThanead** [shawncplus/ranviermud#29]
Hello there,

I'm considering various MUD engines in order to decide which one to use as base for a MUD of my own.

I'm looking for the option to have skill levels, a system where skills get stronger and more effective the more you use them.

Additionally, I'm entertaining the idea of using a leveling system where instead of defeating monsters the player must perform certain actions to gain XP for their class. (I.e., a player of the 'farmer' class must plant crops to gain XP.)

How hard would out be to implement such systems in this engine?

Thanks in advance,
Loid.

**Comment by hath995** [comment]
https://github.com/shawncplus/ranviermud/blob/master/src/player.js
https://github.com/shawncplus/ranviermud/blob/master/src/skills.js

There isn't much of an existing skill system. You could replace it with a different system in an afternoon probably.

**Comment by LoidThanead** [comment]
Thank you for the quick reply! So if I understand you correctly, I would just replace the existing code? There is no way to hook in a new module while leaving the engine itself as is?

**Comment by ingcake** [comment]
If you're developing the system for your own game, as you described, then why *would* you need to keep the old player and skill files? That seems like it would just produce unnecessary confusion for you down the road.

**Comment by seanohue** [comment]
As ingcake implied, just fork the project over and develop your own skill/level system. This project is mostly meant to be a lightweight engine, so there isn't much game logic there (I assume this is intentional).
