### ISSUE TITLE
Softaculous?

### ISSUE THREAD

**Issue by Xarcell** [shawncplus/ranviermud#31]
Once this project hits a comfortable developed stage, perhaps getting it adopted by Softaculous  to make it easier on install? Ghost runs on node.js too, but somehow Softaculous can get it installed on a regular shared server. Perhaps Ranviermud could use the same method?

**Comment by ingcake** [comment]
I don't follow. This project is a lightweight MUD server, so "installation" isn't much of a consideration.  I'm suspicious that it might help if I pointed out the following:
- Ranvier is a server that a MUD could be built upon, not a game itself. It actually caters to multiple game formats - for instance, you could use it to build a real-time MUD or a single player, turn-based text adventure.
- The target "user" is going to be acting as a server administrator. Hence, the user needs to be technically capable of building a game on top of the server; the current installation process isn't remotely comparable to the amount of work that will be required to actually do something with the server. Currently, they (for instance, you or I) don't need to do anything but clone a Git repo, run `npm install` to get dependencies, and then it's a one-liner to get the server running. This is the only "installation" necessary to get the server up and running, as the players only need a telnet client to access the game.
