### ISSUE TITLE
404 link from https://github.com/shawncplus/ranviermud/blob/staging/docs/structure.md

### ISSUE THREAD

**Issue by montsamu** [shawncplus/ranviermud#311]
### Description

https://github.com/shawncplus/ranviermud/blob/staging/docs/structure.md

the "Bundles" link goes to:

https://github.com/shawncplus/ranviermud/blob/staging/extending/bundles

Which does not exist; I think you mean:

https://github.com/shawncplus/ranviermud/blob/staging/docs/extending/bundles.md

If it is all right, I would be happy to try to "fix" this simple issue with a pull request, though I understand it's such a simple fix that might be a bit overkill! Just would get me one step closer to working in the project.

**Comment by montsamu** [comment]
Similarly:

**Comment by shawncplus** [comment]
@montsamu I've labelled these documentation issues as `help-wanted`. They're great beginner issues if you want to make some contributions tot he projects wink wink nudge nudge

**Comment by shawncplus** [comment]
Closing this issue as docs are meant to be viewed after being built by `mkdocs`, not directly on github
