### ISSUE TITLE
With zero classes (or no classes bundle) the create player flow should skip choose class and go to finish

### ISSUE THREAD

**Issue by montsamu** [shawncplus/ranviermud#314]
### Description

Trying to see how far I could trim things down, I removed the classes bundle; the next time I tried to create a player it was a loop of:

Welcome, what is your name? Foobar
Do you want your account's username to be Foobar? [y/n]
Do you want your account's username to be Foobar? [y/n] y
Creating account...
Your password must be at least 8 characters.
Enter your account password:
Confirm your password:
What would you like to name your character? Foobar

Foobar doesn't exist, would you like to create it? [y/n] y

  Pick your class
 --------------------------
>
  Pick your class
 --------------------------
> 1
  Pick your class
 --------------------------
> 0
  Pick your class
 --------------------------
> none
  Pick your class
 --------------------------
> n
  Pick your class
 --------------------------
> no
  Pick your class
 --------------------------
> quit
  Pick your class
 --------------------------

### Expected outcome

With no classes bundle, player create skips choose-class emit and goes straight to finish.

**Comment by shawncplus** [comment]
The default `ranvier-` prefixed bundles aren't really meant to be customized that way. Firstly see the note here in the docs http://ranviermud.com/extending/bundles/#default-bundles Second once you've got your copies that you can customize the way to remove class selection would be to remote the `choose-class` input event, not disable the `ranvier-classes` bundle.
