### ISSUE TITLE
Player equipment not iterable.

### ISSUE THREAD

**Issue by AndrewECooper** [shawncplus/ranviermud#316]
### Log in. Create a character. Error happens when creating / loading the new character.

Issue also happens if you reconnect, log back in, and then select the character you previously created.

### Version of Ranvier: 2.0
2018-01-13T15:02:10.582Z - warn:  TypeError: this.equipment is not iterable
    at Player.serialize (/home/andrew/Projects/ranviermud/src/Player.js:244:39)
    at Player.save (/home/andrew/Projects/ranviermud/src/Player.js:173:41)
    at Quest.instance.on (/home/andrew/Projects/ranviermud/src/QuestFactory.js:47:14)
    at emitOne (events.js:116:13)
    at Quest.emit (events.js:211:7)
    at Quest.emit (/home/andrew/Projects/ranviermud/src/Quest.js:38:11)
    at Quest.instance.on (/home/andrew/Projects/ranviermud/src/QuestFactory.js:52:16)
    at emitNone (events.js:106:13)
    at Quest.emit (events.js:208:7)
    at Quest.emit (/home/andrew/Projects/ranviermud/src/Quest.js:38:11)

-------------------------------------------------------------------------------------------------------------------------------

I'm new to Ranvier. I was trying to test it out but couldn't get past this issue. I fixed the problem but am unsure whether this is the best solution.  I changed the serialize() method on the Player class to the following...

```
serialize() {
    let data = Object.assign(super.serialize(), {
      account: this.account.name,
      experience: this.experience,
      inventory: this.inventory && this.inventory.serialize(),
      metadata: this.metadata,
      password: this.password,
      playerClass: this.playerClass && this.playerClass.id,
      prompt: this.prompt,
      quests: this.questTracker.serialize(),
      role: this.role,
    });

    if (this.equipment) {
      if (!(typeof this.equipment[Symbol.iterator] === "function")) this.equipment = new Map();
      let eq = {};
      for (let [ slot, item ] of this.equipment) {
        eq[slot] = item.serialize();
      }
      data.equipment = eq;
    } else {
      data.equipment = null;
    }

    return data;
  }
```

Right after checking to see if equipment exists, I then check to see if it is iterable. If it isn't, I set it equal to a new Map object. This allows the code to continue. Before, this.equipment was set to something of type object but wasn't iterable.

Note that this problem only happens when the character is first created. Once the character gets past this point the first time it never has this problem again that I can see.

I tried to find a way to fix the issue without altering the Player.js code since it is core. I couldn't really see a way though. Like I said, I'm new to the code base.

**Comment by shawncplus** [comment]
Please pull the latest changes. This should be fixed as of yesterday

**Comment by shawncplus** [comment]
If not hop in the slack and I'll help you debug

**Comment by AndrewECooper** [comment]
Cool.  I'll pull the latest.  Can you send me an invite to the Slack.  I
tried before but never got an invite.

Thanks,

Andrew

**Comment by shawncplus** [comment]
Hmm, you tried this link? https://ranviermud.signup.team

**Comment by AndrewECooper** [comment]
I tried again. I worked this time. Not sure what the problem was before.
Thanks for the link.
