### ISSUE TITLE
How do I add more classes

### ISSUE THREAD

**Issue by wizardsambolton** [shawncplus/ranviermud#39]

**Comment by wizardsambolton** [comment]
@shawncplus

**Comment by marado** [comment]
A quick grep makes me believe that the class list is hardcoded, and you'd have to change `src/events.js` to add more classes.

I guess this issue can/should be seen as "Make the class list configurable".

**Comment by seanohue** [comment]
@wizardsambolton Marado is correct. Check out my fork where I've added 3 custom classes to see how it can be done. I might write some documentation on how to do it, or make it more easily configurable using YML/JSON.

**Comment by Xarcell** [comment]
I wish classes were configurable via YML/JSON, along with list of skills that are meant to be exclusive to that class.

**Comment by seanohue** [comment]
I haven't worked with YML too much outside of editing the files for this MUD, but I'll see if it's possible to set it up to use YML for classes/skills.
