### ISSUE TITLE
How do I add drops

### ISSUE THREAD

**Issue by wizardsambolton** [shawncplus/ranviermud#42]
Hi I have been tinkering with this for the  past weak and I am wandering how do i add npc drops?
oh a no offense @shawncplus but your support is poor and docs are poor. I have opened 4 tickets and got no reply so far and been forced to work it out my self, and there are still some things i havnt work out, and on your docs it says on extending, 'This page will go over how to extend the codebase: adding new commands, new events, new room/player/item properties' and there is nothing about item/room/player properties, so yeah. please get back ASAP

**Comment by shawncplus** [comment]
Some people subscribe to the idea of open source guilt, I don't. If you noticed there hasn't been a commit to this project in over 2 years.

> "please get back ASAP"

You didn't pay for anything and I don't owe you anything.

> "forced to work it out my self" 

Welcome to open source. All of the issues you've opened up can be answered yourself with 5 minutes of grep and a little bit of digging/messing around.

**Comment by wizardsambolton** [comment]
ok fair enough, I was a bit over the top in that comment sorry to bother you, and this is a really great project!
