### ISSUE TITLE
Use another transport instead telnet

### ISSUE THREAD

**Issue by slonoed** [shawncplus/ranviermud#60]
Hello!
This is really nice work here, thank you!

What about change code to work with different transports. For example: using in web, or in chat apps.
I don't talk about implement it, but about ability to switch it easy.

Best regards, Dmitry.

**Comment by shawncplus** [comment]
There would be quite some work involved. Any time player input is accepted there is basically no abstraction from the base telnet library being used so those would have to be updated as well as the server bin itself and initial login event chain. I like the idea though so someone should do that!

**Comment by shawncplus** [comment]
Implemented in 8d9a1783538189054bc239d43d5c6d6f3adf1b0e
