### ISSUE TITLE
Need Group Commands

### ISSUE THREAD

**Issue by Xarcell** [shawncplus/ranviermud#63]
It would be a nice feature if players could travel in groups. 

There should be "Group Open" and "Group Close" commands. When a player's group is open, other players can follow that player ("Follow Player"). The player that is the group leader can "Group Disband" to stop followers without closing his/her group. Also, If a player's group is set to open, you can also be dragged ("Drag Player") which puts them in your group.

**Comment by shawncplus** [comment]
Groups are an interesting feature with a lot of considerations. Joining groups, max group sizes, auto-follow/leave-behind, automatic loot distribution, group kick/ignore/general troll handling, xp scaling, tanking/aggro for real time combat, rank/file for turn based combat. With that said things that don't exist that would be prerequisites for grouping (with a purpose anyway): following, drops, and loot tables.

**Comment by Xarcell** [comment]
Your forgetting the most important reason for grouping. Getting lost. :p
