### ISSUE TITLE
Allow for Node 6

### ISSUE THREAD

**Issue by marado** [shawncplus/ranviermud#75]
Both README and nvmrc state Node 7 is needed for ranvier, but it seems that only 6 is actually needed code-wise.
We should relax the minimum version to 6 to allow users in that version (official Debian package users, for instance) to still run the code.

**Comment by seanohue** [comment]
Is there anything that would need to be poly-filled for usage with Node 6? Maybe Symbols, or object destructuring (though I don't think we use the latter much if at all). If not, this could probably just be a change to the .nvmrc.

**Comment by shawncplus** [comment]
Closing this as the next LTS version of Node has been released (8) so going forward 7.x will be supported for a little while and then Node 8.x will be the supported version
