### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by shawncplus** [shawncplus/ranviermud#77]
Some sort of quest system, a vague 5000 foot details looks like this:

1. Quests and achievements are _very_ similar. They're both systems that watch for _any_ event the player performs and updates some record and after fulfilling a criteria doing something. The only difference is that quests are started at some point and achievements are always active. So should the implementation of quests really instead be some more generic concept that quests and achievements extend from?
2. Should quests be a first class citizen a la rooms/items or should quests be built as a bundle? Personally I think quests being part of the core is the easiest in the long run; in the short run it will take some more thought into making quests modular and extensible enough to allow customization via bundle without having to touch the core.

For me they would be implemented something like this:

Override the `EventEmitter.on` method for `Player` to proxy the event to the quest/achievement system. This to me seems like the most flexible.

Example flow for an achievement:

1. Player gains experience
2. Player `experience` event notices player leveled up
3. `experience` event fires `levelup` event
4. `levelup` event gets proxied to the achievement system
5. achievement system has a `levelup` listener which checks to see player's level is 10
6. achievement system does... something (gives gold/achievement points/temporary buff/anything) in theory each different achievement event could do something different

Example flow for quests:

1. Player sees `[NPC] [!] Guild Leader` indicating that the NPC has a quest the player can take
2. Player executes `quest list leader`
3. `quest` command calls something like `npc.getAvailableQuests(player)` which would loop over all the NPC's quests and check `quest.canStart(player)` which would call a customizable method on the quest to see if the player can start it (Some quests could depend on other quests being finished, or require the player be a certain level, or certain class, etc.)
4. Player executes `quest accept 3` which will mark the given quest as in progress.

For a kill quest "Kill 10 Bandits" which auto-completes:

1. Player kills a bandit
2. Combat event emits `deathblow` event
3. Quest listens for `deathblow` event and checks to see killed NPC's vnum
4. Quest increments its internal state
5. Player kills 9 more bandits.
6. Quest notices player has killed 10 bandits. Quest calls customizable `complete()` method

For a fetch quest "Bring me 5 apples" which only completes when turned in:

1. Player gathers 5 apples
2. Quest is listening for `get` event and notifies the player "You have all the apples you need, return to the Guild Leader"
2. Player returns to NPC and types `quest list` to show his active quests.
3. Player types `quest complete 3` which will, again, call the customizable `complete()` method which in this case removes 5 apples from the players inventory, gives them to the guild leader and gives the player experience.

You can see the power in a system that is completely event based. Literally anything can trigger the start, progress, or completion of events. You can have events which autocomplete, you can have events which are based a player going to a specific room, using a specific command, killing a certain enemy, logging in on a particular day, whatever you want.

**Comment by seanohue** [comment]
I like the idea of making a base concept that Quests and Achievements extend from. The base could even just be an Achievement, and the Quest would just add a concept of an event or prerequisite that begins the quest, as well as potentially being time-based (i.e., slay the dragon within 3 days or the maiden will perish).

In addition, quests could be attached to entities that give them (a special item, a specific room, or an NPC as mentioned in the examples. And each would have different related commands.

If we go down that route, it'd make sense to have the base achievement and quest class in the core and have related commands be in the core-bundle.

**Comment by shawncplus** [comment]
Next step: implementing quest commands and having NPCs be quest givers

**Comment by shawncplus** [comment]
I'm moving Achievements to a separate tasks for the future
