### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by shawncplus** [shawncplus/ranviermud#81]
Implement a rudimentary real time automatic combat system via a `kill` command

**Comment by seanohue** [comment]
Thoughts:

`kill` would place both the player and the target (if one exists in the same room) into each others `inCombat` lists (list assuming that multi-entity combat will be a thing). A `combatTick` would fire every 1/2 second and, based on the combatants' speed, they might attack or do nothing, until one of them is dead (so, this card would also assume some kind of post-death cleanup for both NPCs and players).

In this iteration, combat damage would be related solely to gear.

Possible issues: 

How would we "stagger" the attacks between the player and target? Even if they are the same speed, it would seem odd to have them attack at the same time. Maybe some kind of initiative roll at the start of combat, or maybe the aggressor gets the first attack immediately while the other has to wait a few ticks to respond.

**Comment by shawncplus** [comment]
Implemented in the `core-combat` bundle
