### ISSUE TITLE
Coordinate based room system?

### ISSUE THREAD

**Issue by shawncplus** [shawncplus/ranviermud#98]
I've been thinking about making the room system coordinate based. So when you're building rooms you don't even specify standard cardinal exits, the coordinate system does it for you. If you want non-euclidean  exits (i.e., portals to non-connecting rooms) that should still be supported. But I think a coordinate system lends itself much better for building, player expectations of their surroundings, and for the possibility of say mapping features outside of a trivial AFKMud style compass.

**Comment by marado** [comment]
https://github.com/marado/Nodiverse might be useful for this.

**Comment by seanohue** [comment]
I like the idea of this, as @marado points out it could make it easier to use tools such as nodiverse or ROT-js to generate areas procedurally. I like the idea of keeping the actual generation tools out of the ranvier framework but having a coordinate-based system would make it easier to use them.

How would neighboring rooms that do not have a door between them be implemented? Would a wall be represented by coordinates that are not filled in? If so, that would make sense and be perfect for implementing rogue-like mapping systems. 

For instance, a 4 x 4 map:
```
##-#
-#-#
---#
####
```

With the bottom left coord being (0,0), and the `#` symbols marking areas that are not rooms, this means that room (0, 2) would be a room with exits to the south and, i assume, the southeast?

That makes sense but I would also like the possibility of specifying somehow that there is _not_ an exit to the southeast, but only south, in addition to specifying non-euclidean travel such as a portal from (0,2) through the wall to (2, 2).

**Comment by marado** [comment]
In Nodiverse, 2D maps are represented like this:
```
 c - d
 | / 
 a - b
```
the dashes and slashes representing passages, ie, you can go from d to a by moving sw, but in d you cannot go south, because while there's a room there (b), there's no passage.
Adding different ways a ASCII representation of a map (either 2D or 3D) is easy: while the current functions are designed in a way where you only define the number of dimensions (2D or 3D map), the center tile and the size of the map, all the drawing is made in one included .js only, and writing a different function for 2D maps (or even allowing the user to choose the map style) is trivial: check https://github.com/marado/Nodiverse/blob/master/asciimap.js#L197 to see how a tile (room) is currently drawn.

Advantages of Nodiverse over ROT.js is that in Nodiverse a wall (or lack of passage) doesn't occupy a tile, you can move not only NSWE but also NW, NE, SW and SE, and extending the universe properties is as easy as adding objects or properties to the universe itself (if you want to create the concept of bidirectional portals, for instance, you just drop a reference to that portal on each end's tile).

And, of course, any suggestion or criticism to Nodiverse is more than appreaciated, as well as PRs, issues, etc :-)

**Comment by dannytatom** [comment]
So any update on this? I'm wanting to use ranvier for an idea, but don't really wanna start until this is done so I can avoid redoing a ton of areas. Plus I'd like to be able to have proc gen areas as well as drawing a map to screen.

I'm down to help out if we can get a conversation/plan going.

**Comment by shawncplus** [comment]
There was quite a long discussion the other day. It boiled down to this which is my current plan:

Every area will be able to define each area as its own x/y/z plane with its own 0,0,0 origin.

The following questions arise:

* How should exits be specified?
** Option 1. Just as they are now, each rooms specifies each of its exits which creates a lot of weirdness in that it's just as easy to create a completely unmappable non-euclidean disaster. Stitching together the world, mapping, overlap detection, and pathing would be just as impossible as they are now.
** Option 2. Rooms can no longer specify their exits (though could still specify doors and such.) A new file in something like `data/areas.yml` would be created to enumerate all the areas and where they connect by specifying an origin offset for the area. So if you want to connect Area A (3, 4, 0) at Area B (-2, 3, ) the origin is xB - xA/yB - yA/zB - zA so the origin offset you would configure would be (-5, -1, 0). This has the benefit of creating nice euclidean geometry which can be mapped and pathed and visualized very easily. The downside is you are _forced_ to create euclidean geometry, for example you would no longer be able to create a room with an exit that says east but actually takes you west.

I personally lean towards option 2. It just makes everything simpler though at the cost of being able to do really wacky shit no one wanted to do anyway.

To make either this at all usable some kind of tool would have to exist to graph the actual rooms so an initial implementation could be a super trivial switch like `./ranvier --render-areas` and that could output a PNG graphing out all the rooms

**Comment by marado** [comment]
Option 2 FTW, its only downside is actually an upside for me :-)

**Comment by seanohue** [comment]
Regarding option #2: If you want to do non-euclidean portals, you could still do so with a room script or behavior; it would not be picked up by the coordinate/mapping system.

**Comment by dannytatom** [comment]
I vote option 2, little confused tho so maybe you could clarify.

So rooms no longer have exits, but instead have a (x, y, z) `location` relevant to the area (so each area has it's own, self-contained coordinate system going on). I don't really get the part about connecting areas, though.

It seems simplest to have each area be it's own thing, with no location or anything, just existing in a void. A room from Area A could connect to a room in Area B like `connects: "AreaB:x,y,z"` in the yaml. Basically a portal, like @seanohue was saying.

**Comment by thedandroid** [comment]
I'm also confused on the rooms no longer having specified exits.

**Comment by shawncplus** [comment]
@dannytatom "A room from Area A could connect to a room in Area B like connects: "AreaB:x,y,z" in the yaml." The problem with this is that it allows you to create completely chaotic non-euclidean geometry. Let's make a simple example. You have two 6x6x1 areas and both have all rooms full. If I want to connect A6,6,0 (bottom right corner) to B0,0,0 (top left) that's really easy. But what if someone does something insane like connect A0,0,0 to B0,0,0? You can't map that anymore because you've essentially "forked" the universe they overlap each other when coming from some directions but not from others?

**Comment by shawncplus** [comment]
@thedandroid they wouldn't need to specify their exits because it can be inferred from their coordinates. If I have 0,0,0 and a 0,1,0 it's inferred that I can go north from 0,0,0 to 0,1,0 and vice versa

**Comment by marado** [comment]
So, walls/doors aren't a thing?

What if I want to have rooms 0,0; 0,1; 1,0 and 1,1, but with a wall? ie.,
```
 __
|_  |
|__|
```

**Comment by shawncplus** [comment]
The wall would occupy space, you'd have. 0,0 as room 1. the "wall" would "occupy" 0,1 (meaning you just wouldn't put a room at 0,1. And room 2 would be 0,2. Walls are, therefor, empty space. Alternatively there could be a config option made that said "Hey, don't allow this room to connect south." which would block navigation to that room to or  from the south but first things first I think.

**Comment by dannytatom** [comment]
@shawncplus Ah, ok, so I think I understand. When I was thinking about mapping I didn't think area connections really mattered. I was thinking of areas as similar to island, self contained places not directly connected to other areas.

**Comment by dannytatom** [comment]
@marado You could just not have a room at 0,1 and it would create a wall for you. But then we'd need options for defaults, since in outside areas maybe no coordinate means "forest."

**Comment by shawncplus** [comment]
@marado yes, you would need an extra room to let the player walk around to the other side. So instead of walking `e s w` they would have to walk `e s s w`

**Comment by shawncplus** [comment]
Me right now http://i0.kym-cdn.com/entries/icons/original/000/022/524/tumblr_o16n2kBlpX1ta3qyvo1_1280.jpg

**Comment by dannytatom** [comment]
same tbh

**Comment by marcelomoreli** [comment]
My vote is for not implementing this at all. Too much trouble for a few gain.

**Comment by dannytatom** [comment]
idk, i think the gain is pretty huge. if it's based on a coordinate system it's easier to have generated areas, map builders, show maps in game, etc.

could code up a cave generator, run it, then manually add a few specific rooms way faster than creating a ton of the same "cave floor" room and connecting them manually over and over again.

all those *could* be done with the current system, but seems way harder to do. especially being able to have `look` show you a map of the area and where you are in it.

**Comment by shawncplus** [comment]
I agree with danny that there is huge gains: you can actually map the world which means you can actually have pathing because with euclidean geometry you can just throw math at it. Want to have an NPC walk from room A to room B? Well just give him the start and end coordinates and he'll math his way over there. You can actually draw the game world. Like danny said you can use maze generation algorithms to randomly generate sane areas, you can do awesome stuff like apply travel costs to certain rooms based on type such that you can develop a custom weighted manhattan distance heuristic so that if you have a quest that takes you from A to B and there is a swamp in between the "autowalk" feature will walk _around_ the swamp.

**Comment by ratacat** [comment]
Interesting conversation all..I really like the coordinate system.  I'm super glad you went for it @shawncplus !  I am really wanting to be able to implement walls though, and I'd like to figure out a way to do it that wouldn't totally destroy the pathing, but that is seeming a bit unlikely the more I dig into it.
